name: docs

on:
    # 每当 push 到 main 分支时触发部署
    push:
        branches: [main]
    # 手动触发部署
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  # 选择要使用的 node 版本
                  node-version: 18
                  # 缓存 pnpm 依赖
                  # cache: pnpm

            - name: 缓存目录 node_modules
              id: cache-node-modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-18-nodeModules-${{ hashFiles('package-lock.json') }}-${{ hashFiles('package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-18-nodeModules-

            - name: 安装依赖
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm install

            - name: 构建vuepress
              run: npm run build

            - name: 发布到分支page
              uses: crazy-max/ghaction-github-pages@v3
              with:
                  # 部署到 page 分支
                  target_branch: page
                  # 部署目录为 VuePress 的默认输出目录
                  build_dir: docs/.vuepress/dist
              env:
                  # 使用 GITHUB_TOKEN 进行身份验证
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
